kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: israfilalam22/drone_dev
    username:
      from_secret: israfilalam22
    password:
      from_secret: Israfil@#!98#@A
    tags: 
      - latest
